version: "3"
services:
  front:
    image: node:14
    volumes:
      - ./front/:/usr/src/app
    working_dir: /usr/src/app
    environment: 
      - REACT_NATIVE_PACKAGER_HOSTNAME=163.51.23.145
    command: yarn start
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"




